struct TheCountry* addNewCountry(struct TheCountry* country);
void outputArray(struct TheCountry* country);
void outputAllNotes(struct TheCountry* country);
void outputOneNote(struct TheCountry* country);
void editing(struct TheCountry* country);
void delete(struct TheCountry* country);
void search(struct TheCountry* country);
void searchGivenParam(struct TheCountry* country);
void partSearch(struct TheCountry* country);
int menu();
int inputValidationInt();
float inputValidationFloat();
int correctChoice (int k);
void lines();
void headline();
int editingMenu();
int startMenu();
int searchMenu();
void coercion(char*string);
