int inputValidationInt();
int correctChoice(int k);
int unionMenu();
int startMenu();
int paramEditMenu();
int menu();
void lines();
void headline();
void rightRegister(char*string, int stringSize);
struct TheBook* addBooks(struct TheBook* pointer);
struct TheBook* del (struct TheBook* pointer);
struct TheBook* delGivenParam(struct TheBook* pointer);
struct TheBook * addNewBooks(struct TheBook * pointer);
void outputArray(struct TheBook * pointer);
void partEdit(struct TheBook *pointer);
void editOneNote (struct TheBook *pointer);
void searchOutput (struct TheBook *pointer, int bookNumber);
void search (struct TheBook* pointer);
void edit(struct TheBook * pointer);
void ascendingSort (struct TheBook *pointer);
void descendingSort (struct TheBook *pointer);
void alphabeticallySort(struct TheBook * pointer);
void sort(struct TheBook* pointer);